version: '3'
services:
  app1:
    build:
      context: ./app1
    container_name: test_app1
    ports:
      - 8080:8080
  app2:
    build: 
      context: ./app2
    container_name: test_app2
    ports:
      - 8081:8081


