version: '3' # docker-composeのバージョンを指定
services:
  php:
    container_name: "php"
    build:
      context: ./app
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www/html
  nginx: # サービス名
    container_name: "nginx" # コンテナ名
    build:
      context: ./nginx
    links: # ここで指定したサービス名とのリンクを作成する
      - php # サービス名”php”と”nginx”を関連付ける

